<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Práctica dirigida 11</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas Estadística_1</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="intro.html">Introducción</a>
</li>
<li>
  <a href="basico.html">Procedimientos básicos</a>
</li>
<li>
  <a href="pd1.html">Práctica 1</a>
</li>
<li>
  <a href="pd2.html">Práctica 2</a>
</li>
<li>
  <a href="pd3.html">Práctica 3</a>
</li>
<li>
  <a href="pd4.html">Práctica 4</a>
</li>
<li>
  <a href="pd5.html">Práctica 5</a>
</li>
<li>
  <a href="pd6.html">Práctica 6</a>
</li>
<li>
  <a href="pd7.html">Práctica 7</a>
</li>
<li>
  <a href="pd8.html">Práctica 8</a>
</li>
<li>
  <a href="pd9.html">Práctica 9</a>
</li>
<li>
  <a href="pd10.html">Práctica 10</a>
</li>
<li>
  <a href="pd11.html">Práctica 11</a>
</li>
<li>
  <a href="pd12.html">Práctica 12</a>
</li>
<li>
  <a href="pd13.html">Práctica 13</a>
</li>
<li>
  <a href="FAQ.html">FAQ</a>
</li>
<li>
  <a href="https://github.com/arturomaldonado/PracticasPOL278">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Práctica dirigida 11</h1>

</div>


<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" /></p>
<pre class="r"><code>library(rio)
library(haven)
library(tidyverse)
library(scales)
library(ggplot2)
library(fastDummies)
library(jtools)
library(lsr)</code></pre>
<div id="repaso" class="section level1">
<h1><strong>Repaso</strong></h1>
<p>Para la sesión de hoy haremos un repaso de todos los temas que hemos
visto luego del parcial, siendo estos:</p>
<ol style="list-style-type: decimal">
<li>Anova</li>
<li>Correlación</li>
<li>Regresión simple</li>
<li>Regresión múltiple</li>
</ol>
<p>En esta oportunidad usaremos la información proveniente de la
encuesta realizada por Lima Cómo Vamos, de la cual podemos obtener
evidencia sobre la calidad de vida en Lima y Callao.</p>
</div>
<div id="aplicación-práctica" class="section level1">
<h1>Aplicación práctica</h1>
<pre class="r"><code>data = import(&quot;BD_LimaComoVamos2021.sav&quot;)</code></pre>
<div id="anova" class="section level2">
<h2>Anova</h2>
<p><em>¿Existe diferencia entre los promedios de la satisfacción con
aspectos que influyen en la calidad de vida en la ciudad (indicador
creado con las variables de la P3_1 a la P3_8) según el nivel
socioeconómico de una persona (NSE)?</em></p>
<p>Para responder a la pregunta, primero se deben identificar las
variables: variable 1: inclusión (indicador -&gt; numérica) variable 2:
nivel socioeconómico (categórica politómica)</p>
<p>Prueba a realizar: Anova</p>
<ol style="list-style-type: decimal">
<li>Preparar las variables (creación del indicador / configuración de
las etiquetas)</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Creación del indicador</li>
</ol>
<pre class="r"><code>str(data$P3_1)</code></pre>
<pre><code>##  num [1:1117] 1 1 2 1 1 1 2 3 1 2 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_1)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 643 229 191  30  22</code></pre>
<pre class="r"><code>str(data$P3_2)</code></pre>
<pre><code>##  num [1:1117] 1 1 4 1 2 3 4 1 1 3 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_2)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 397 302 303  76  31</code></pre>
<pre class="r"><code>str(data$P3_3)</code></pre>
<pre><code>##  num [1:1117] 1 1 3 1 4 3 5 2 3 4 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_3)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 288 239 336 175  78</code></pre>
<pre class="r"><code>str(data$P3_4)</code></pre>
<pre><code>##  num [1:1117] 1 1 5 1 1 2 5 2 1 4 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_4)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 386 309 264 118  40</code></pre>
<pre class="r"><code>str(data$P3_5)</code></pre>
<pre><code>##  num [1:1117] 2 1 5 1 1 3 3 3 2 3 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_5)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 293 286 337 119  43</code></pre>
<pre class="r"><code>str(data$P3_6)</code></pre>
<pre><code>##  num [1:1117] 3 1 4 1 1 2 4 3 2 3 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_6)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 405 297 293  80  37</code></pre>
<pre class="r"><code>str(data$P3_7)</code></pre>
<pre><code>##  num [1:1117] 3 1 3 2 4 4 5 3 3 4 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_7)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 130 175 341 334 134</code></pre>
<pre class="r"><code>str(data$P3_8)</code></pre>
<pre><code>##  num [1:1117] 1 1 3 1 4 3 1 2 2 3 ...
##  - attr(*, &quot;label&quot;)= chr &quot;P3_1.       (MOSTRAR TARJETA) En una escala del 1 al 5, donde 1 significa nada satisfecho y 5 muy satisfecho ¿c&quot;| __truncated__
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F8.0&quot;</code></pre>
<pre class="r"><code>table(data$P3_8)</code></pre>
<pre><code>## 
##   1   2   3   4   5 
## 302 279 345 136  52</code></pre>
<pre class="r"><code>data = data %&gt;%
  mutate(
    suma = P3_1 + P3_2 + P3_3 + P3_4 + P3_5 + P3_6 + P3_7 + P3_8,
    satisfaccion = rescale(suma, to = c(0,100))
  )</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Etiquetas para el nivel socioeconómico</li>
</ol>
<pre class="r"><code>data = data %&gt;%
  mutate(
    NSE = factor(NSE, labels=c(&quot;NSE A&quot;, &quot;NSE B&quot;, &quot;NSE C&quot;, &quot;NSE D&quot;, &quot;NSE E&quot;))
  )</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Análisis descriptivo</li>
</ol>
<pre class="r"><code>tabla1 = data %&gt;%
  group_by(NSE) %&gt;%
  summarise(Media = mean(satisfaccion, na.rm = T),
            Mediana = median(satisfaccion, na.rm = T),
            Desviacion = sd(satisfaccion, na.rm = T),
            Inferior = ciMean(satisfaccion, na.rm = T)[1],
            Superior = ciMean(satisfaccion, na.rm = T)[2])

tabla1</code></pre>
<pre><code>## # A tibble: 5 × 6
##   NSE   Media Mediana Desviacion Inferior Superior
##   &lt;fct&gt; &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 NSE A  38.2    37.5       16.1     33.9     42.5
## 2 NSE B  35.9    37.5       16.6     33.9     37.9
## 3 NSE C  34.3    34.4       18.4     32.7     35.9
## 4 NSE D  27.9    25         18.8     25.1     30.7
## 5 NSE E  27.0    18.8       22.2     19.0     34.9</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Realización de la prueba</li>
</ol>
<p>*Recuerda redactar tus hipótesis</p>
<p>H0: No existe diferencia en el promedio de satisfacción con aspectos
que influyen en la calidad de vida de ningún nivel socioeconómico</p>
<p>H1: Al menos un nivel socioeconómico tiene un promedio de
satisfacción con aspectos que influyen en la calidad de vida diferente
al resto</p>
<pre class="r"><code>anova = aov(data$satisfaccion ~ data$NSE)
summary(anova)</code></pre>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## data$NSE       4  10175  2543.8   7.826 3.24e-06 ***
## Residuals   1058 343904   325.1                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 54 observations deleted due to missingness</code></pre>
<p>Siendo el p-valor menor a 0.05, es posible afirmar que al menos un
grupo tiene un promedio de satisfacción con aspectos que influyen en la
calidad de vida diferente al resto, pero todavía no podemos saber cuál.
Para averiguar esto último debemos realizar la prueba Tukey, pero antes
observaremos un poco los resultados obtenidos hasta el momento.</p>
<pre class="r"><code>ggplot(tabla1,aes(x=NSE,y=Media))+
  geom_errorbar(aes(ymin=Inferior,ymax=Superior),width=0.4)+
  xlab(&quot;Nivel socioeconómico&quot;)+
  ylab(&quot;Percepción sobre la satisfacción&quot;)+theme_classic()</code></pre>
<p><img src="pd11_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>El gráfico anterior permite observar que, por lo general, los niveles
soecioeconómicos más bajos tienen menor satisfacción con aspectos que
influyen en la calidad de vida de la ciudad.</p>
<ol start="4" style="list-style-type: decimal">
<li>Prueba post-hoc</li>
</ol>
<pre class="r"><code>comparacion = TukeyHSD(anova)
comparacion</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = data$satisfaccion ~ data$NSE)
## 
## $`data$NSE`
##                    diff        lwr        upr     p adj
## NSE B-NSE A  -2.3149920  -9.484662  4.8546781 0.9034677
## NSE C-NSE A  -3.8975852 -10.769860  2.9746895 0.5302456
## NSE D-NSE A -10.3525498 -17.855253 -2.8498464 0.0016112
## NSE E-NSE A -11.2595943 -22.141789 -0.3773995 0.0383985
## NSE C-NSE B  -1.5825932  -5.253399  2.0882132 0.7640005
## NSE D-NSE B  -8.0375578 -12.784896 -3.2902199 0.0000411
## NSE E-NSE B  -8.9446023 -18.146169  0.2569640 0.0613728
## NSE D-NSE C  -6.4549646 -10.739962 -2.1699667 0.0003989
## NSE E-NSE C  -7.3620091 -16.333788  1.6097696 0.1650693
## NSE E-NSE D  -0.9070445 -10.370406  8.5563170 0.9989657</code></pre>
<p>Luego de realizar la prueba Tukey, es posible observar que existen
diferencias significativas en el promedio de satisfacción con aspectos
que influyen en la calidad de vida de distintos grupos, siendo
estos:</p>
<ul>
<li>NSE D y NSE A</li>
<li>NSE E y NSE A</li>
<li>NSE D y NSE B</li>
<li>NSE D y NSE C</li>
</ul>
<p>*Recuerda que para graficar los resultados de la prueba Tukey debes
seguir estos pasos:</p>
<ol style="list-style-type: decimal">
<li>Creación de la tabla</li>
</ol>
<pre class="r"><code>comparacion.df = as.data.frame(comparacion[1])
comparacion.df$comparacion = rownames(comparacion.df)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Graficar</li>
</ol>
<pre class="r"><code>ggplot(comparacion.df, aes(x=comparacion, y=data.NSE.diff))+
  geom_errorbar(aes(ymin=data.NSE.lwr, ymax=data.NSE.upr), width=0.2)+
  geom_text(aes(label=paste(round(data.NSE.diff, 1))), vjust=-1, size=3)+
  xlab(&quot;Comparación&quot;) + ylab(&quot;Diferencia&quot;)+
  coord_flip() +
  geom_hline(yintercept = 0, color = &quot;red&quot;, linetype=&quot;dotted&quot;) +
  theme_classic()</code></pre>
<p><img src="pd11_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>*Ten presente que para interpretar el gráfico debemos obsevar las
agrupaciones que no traslapen al interpceto 0.</p>
</div>
<div id="correlación" class="section level2">
<h2>Correlación</h2>
<p><em>¿Existe relación entre la satisfacción con aspectos que influyen
en la calidad de vida y la edad (DC2)?</em></p>
<p>Para responder a la pregunta, primero se deben identificar las
variables: variable 1: satisfacción (indicador -&gt; numérica) variable
2: edad (numérica)</p>
<p>Prueba a realizar: Correlación</p>
<ol style="list-style-type: decimal">
<li>Exploración de variables</li>
</ol>
<pre class="r"><code>data %&gt;%
 summarize(Min = min(satisfaccion, na.rm = TRUE),
           Media = mean(satisfaccion, na.rm = TRUE),
           Mediana = median(satisfaccion, na.rm = TRUE),
           Max = max(satisfaccion, na.rm = TRUE))</code></pre>
<pre><code>##   Min    Media Mediana Max
## 1   0 33.63711  34.375 100</code></pre>
<pre class="r"><code>data %&gt;%
 summarize(Min = min(DC2, na.rm = TRUE),
           Media = mean(DC2, na.rm = TRUE),
           Mediana = median(DC2, na.rm = TRUE),
           Max = max(DC2, na.rm = TRUE))</code></pre>
<pre><code>##   Min    Media Mediana Max
## 1  18 40.27126      38  88</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Prueba de correlación</li>
</ol>
<p>H0: No existe relación entre la satisfacción con aspectos que
influyen en la calidad de vida en la ciudad y la edad</p>
<p>H1: Sí existe relación entre la satisfacción con aspectos que
influyen en la calidad de vida en la ciudad y la edad</p>
<pre class="r"><code>cor.test(x=data$satisfaccion, y=data$DC2, method=&quot;pearson&quot;)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  data$satisfaccion and data$DC2
## t = -5.6856, df = 1061, p-value = 1.684e-08
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.2297032 -0.1129919
## sample estimates:
##        cor 
## -0.1719508</code></pre>
<p>Siendo el p-valor menor a 0.05 se rechaza la H0, por tanto, es
posible afirmar que la satisfacción con aspectos que influyen en la vida
de la ciudad y la edad de una persona están relacionadas.
Adicionalmente, debe mencionarse que esta relación es negativa y
pequeña. Lo anterior se refiere a que a medida que una persona tiene más
edad, puede también sentir una menor satisfacción con aspectos que
influyen en la calidad de vida en la ciudad. Sin embargo, la debilidad
de esta correlación indica que la edad no es el único factor
determinante y que cambios en la edad no necesariamente llevan a cambios
significativos en la satisfacción con los aspectos considerados.</p>
<p>*¿Qué pasa si sale mayor a 0.05? En este escenario no se rechaza la
hipótesis nula y por tanto, no se puede afirmar que exista relación
entre las variables ni tampoco lo contrario. Por tanto, no debe
interpretarse ni la fuerza ni el sentido (no sabemos si esa relación
existe).</p>
<p>**Interpretación del cor Con el signo se ve el sentido de la
relación. Es decir, si es directa o inversa (si el signo es positivo o
negativo). Con el valor se ve la fuerza de la relación. Es decir, si es
no relevante (0.0 a menos de 0.1), pequeña (de 0.1 a menos de 0.3),
mediana (de 0.3 a menos de 0.5) o grande (de 0.5 a 1)</p>
<ol start="3" style="list-style-type: decimal">
<li>Gráfico de dispersión</li>
</ol>
<pre class="r"><code>ggplot(data, aes(x=DC2, y=satisfaccion))+
  geom_point(colour=&quot;skyblue&quot;)+
  labs(x=&quot;Edad&quot;, 
       y=&quot;Satisfacción con aspectos que influyen \n en la calidad de vida&quot;) + 
  ggtitle(&quot;Relación entre la satisfacción con aspectos que \n influyen en la calidad de vida y la edad&quot;) +
  theme_light()+ geom_smooth(method=lm,se=F)</code></pre>
<p><img src="pd11_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code>  theme_light()</code></pre>
<pre><code>## List of 97
##  $ line                      :List of 6
##   ..$ colour       : chr &quot;black&quot;
##   ..$ linewidth    : num 0.5
##   ..$ linetype     : num 1
##   ..$ lineend      : chr &quot;butt&quot;
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ rect                      :List of 5
##   ..$ fill         : chr &quot;white&quot;
##   ..$ colour       : chr &quot;black&quot;
##   ..$ linewidth    : num 0.5
##   ..$ linetype     : num 1
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ text                      :List of 11
##   ..$ family       : chr &quot;&quot;
##   ..$ face         : chr &quot;plain&quot;
##   ..$ colour       : chr &quot;black&quot;
##   ..$ size         : num 11
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : num 0
##   ..$ lineheight   : num 0.9
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ title                     : NULL
##  $ aspect.ratio              : NULL
##  $ axis.title                : NULL
##  $ axis.title.x              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 2.75points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.title.x.top          :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 2.75points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.title.x.bottom       : NULL
##  $ axis.title.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 2.75points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.title.y.left         : NULL
##  $ axis.title.y.right        :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 0points 2.75points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text                 :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr &quot;grey30&quot;
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.x               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 2.2points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.x.top           :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 2.2points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.x.bottom        : NULL
##  $ axis.text.y               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 1
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 2.2points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.y.left          : NULL
##  $ axis.text.y.right         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 0points 2.2points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.ticks                :List of 6
##   ..$ colour       : chr &quot;grey70&quot;
##   ..$ linewidth    : &#39;rel&#39; num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ axis.ticks.x              : NULL
##  $ axis.ticks.x.top          : NULL
##  $ axis.ticks.x.bottom       : NULL
##  $ axis.ticks.y              : NULL
##  $ axis.ticks.y.left         : NULL
##  $ axis.ticks.y.right        : NULL
##  $ axis.ticks.length         : &#39;simpleUnit&#39; num 2.75points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ axis.ticks.length.x       : NULL
##  $ axis.ticks.length.x.top   : NULL
##  $ axis.ticks.length.x.bottom: NULL
##  $ axis.ticks.length.y       : NULL
##  $ axis.ticks.length.y.left  : NULL
##  $ axis.ticks.length.y.right : NULL
##  $ axis.line                 : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ axis.line.x               : NULL
##  $ axis.line.x.top           : NULL
##  $ axis.line.x.bottom        : NULL
##  $ axis.line.y               : NULL
##  $ axis.line.y.left          : NULL
##  $ axis.line.y.right         : NULL
##  $ legend.background         :List of 5
##   ..$ fill         : NULL
##   ..$ colour       : logi NA
##   ..$ linewidth    : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ legend.margin             : &#39;margin&#39; num [1:4] 5.5points 5.5points 5.5points 5.5points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ legend.spacing            : &#39;simpleUnit&#39; num 11points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ legend.spacing.x          : NULL
##  $ legend.spacing.y          : NULL
##  $ legend.key                :List of 5
##   ..$ fill         : chr &quot;white&quot;
##   ..$ colour       : logi NA
##   ..$ linewidth    : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ legend.key.size           : &#39;simpleUnit&#39; num 1.2lines
##   ..- attr(*, &quot;unit&quot;)= int 3
##  $ legend.key.height         : NULL
##  $ legend.key.width          : NULL
##  $ legend.text               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ legend.text.align         : NULL
##  $ legend.title              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ legend.title.align        : NULL
##  $ legend.position           : chr &quot;right&quot;
##  $ legend.direction          : NULL
##  $ legend.justification      : chr &quot;center&quot;
##  $ legend.box                : NULL
##  $ legend.box.just           : NULL
##  $ legend.box.margin         : &#39;margin&#39; num [1:4] 0cm 0cm 0cm 0cm
##   ..- attr(*, &quot;unit&quot;)= int 1
##  $ legend.box.background     : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ legend.box.spacing        : &#39;simpleUnit&#39; num 11points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ panel.background          :List of 5
##   ..$ fill         : chr &quot;white&quot;
##   ..$ colour       : logi NA
##   ..$ linewidth    : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ panel.border              :List of 5
##   ..$ fill         : logi NA
##   ..$ colour       : chr &quot;grey70&quot;
##   ..$ linewidth    : &#39;rel&#39; num 1
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ panel.spacing             : &#39;simpleUnit&#39; num 5.5points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ panel.spacing.x           : NULL
##  $ panel.spacing.y           : NULL
##  $ panel.grid                :List of 6
##   ..$ colour       : chr &quot;grey87&quot;
##   ..$ linewidth    : NULL
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ panel.grid.major          :List of 6
##   ..$ colour       : NULL
##   ..$ linewidth    : &#39;rel&#39; num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ panel.grid.minor          :List of 6
##   ..$ colour       : NULL
##   ..$ linewidth    : &#39;rel&#39; num 0.25
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ panel.grid.major.x        : NULL
##  $ panel.grid.major.y        : NULL
##  $ panel.grid.minor.x        : NULL
##  $ panel.grid.minor.y        : NULL
##  $ panel.ontop               : logi FALSE
##  $ plot.background           :List of 5
##   ..$ fill         : NULL
##   ..$ colour       : chr &quot;white&quot;
##   ..$ linewidth    : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ plot.title                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 1.2
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 5.5points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.title.position       : chr &quot;panel&quot;
##  $ plot.subtitle             :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 5.5points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.caption              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : num 1
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 5.5points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.caption.position     : chr &quot;panel&quot;
##  $ plot.tag                  :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 1.2
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.tag.position         : chr &quot;topleft&quot;
##  $ plot.margin               : &#39;margin&#39; num [1:4] 5.5points 5.5points 5.5points 5.5points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ strip.background          :List of 5
##   ..$ fill         : chr &quot;grey70&quot;
##   ..$ colour       : logi NA
##   ..$ linewidth    : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ strip.background.x        : NULL
##  $ strip.background.y        : NULL
##  $ strip.clip                : chr &quot;inherit&quot;
##  $ strip.placement           : chr &quot;inside&quot;
##  $ strip.text                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr &quot;white&quot;
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 4.4points 4.4points 4.4points 4.4points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ strip.text.x              : NULL
##  $ strip.text.x.bottom       : NULL
##  $ strip.text.x.top          : NULL
##  $ strip.text.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ strip.text.y.left         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ strip.text.y.right        : NULL
##  $ strip.switch.pad.grid     : &#39;simpleUnit&#39; num 2.75points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ strip.switch.pad.wrap     : &#39;simpleUnit&#39; num 2.75points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;theme&quot; &quot;gg&quot;
##  - attr(*, &quot;complete&quot;)= logi TRUE
##  - attr(*, &quot;validate&quot;)= logi TRUE</code></pre>
<p>Es posible observar que la relación entre ambas variables es negativa
y pequeña. Esto debido a que la recta se posiciona de manera descendente
y por la gran dispersión de los puntos.</p>
</div>
<div id="regresión-simple" class="section level2">
<h2>Regresión simple</h2>
<p><em>Crea un modelo para predecir los valores de la satisfacción con
aspectos que influyen en la calidad de vida en la ciudad según la
satisfacción que se tiene conaspectos relacionados al cuidado del medio
ambiente</em></p>
<p>Para lo anterior, primero tendremos que crear otro indicador, siendo
este:</p>
<pre class="r"><code>data = data %&gt;%
  mutate(
    suma2 = I_1_P13 + I_2_P13 + I_3_P13 + I_4_P13 + I_5_P13 + I_6_P13 + I_7_P13 + I_8_P13,
    sostenibilidad = rescale(suma2, to = c(0,100))
  )</code></pre>
<ol style="list-style-type: decimal">
<li>Crear el modelo</li>
</ol>
<pre class="r"><code>modelo1 = lm(satisfaccion ~ sostenibilidad, data = data)
summary(modelo1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = satisfaccion ~ sostenibilidad, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.809  -9.783   0.140   9.829  48.658 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    12.74739    0.95367   13.37   &lt;2e-16 ***
## sostenibilidad  0.58760    0.02334   25.18   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.98 on 952 degrees of freedom
##   (163 observations deleted due to missingness)
## Multiple R-squared:  0.3997, Adjusted R-squared:  0.3991 
## F-statistic: 633.9 on 1 and 952 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Interpretamos</li>
</ol>
<p>A. Validez del modelo: debido a que el p-valor es menor a 0.05, se
puede afirmar que el modelo tiene validez.</p>
<p>*Al ser esta una regresión simple. Se puede afirmar que la variable X
(indicador de satisfacción con aspectos relacionados al medio ambiente)
usada para predecir la variable Y (indicador de satisfacción con
aspectos que influyen en la calidad de vida en la ciudad) están
relacionadas.</p>
<p>B. Explicación del modelo: el modelo indica que aproximadamente el
39.97% (Multiple R-squared) de la variabilidad en la satisfacción con
aspectos que influyen en la calidad de la ciudad puede ser explicada por
la satisfacción con aspectos relacionados con el medio ambiente.</p>
<p>*Recuerda que lo anterior representa la cantidad de variabilidad en
los valores de Y que es capturada por el modelo de regresión. En ese
contexto, cuanto más cercano esté el valor a 1, mayor será la proporción
de la variabilidad explicada por el modelo.</p>
<p>C. Identificación e interpretación de la constante/intersección y la
pendiente/coeficiente: - Constante/ intersección: 12.74739 - Pendiente/
coeficiente: 0.58760</p>
<p>De ese modo, es posible afirmar que si la satisfacción con aspectos
relacionados con el medio ambiente es 0, el valor de la satisfacción con
aspectos que influyen en la calidad de vida es 12.74739, mientras que
por cada punto adicional en el indicador de sostenibilidad, el valor del
indicador de satisfacción con aspectos que influyen en la calidad de
vida en la ciudad aumenta en 0.58760.</p>
<p>D. Ecuación de la recta:</p>
<p>Y = 12.74739 + 0.58760 (X)</p>
<p>E. Predecir <em>¿Cuál será la satisfacción con aspectos que influyen
en la calidad de vida de la ciudad si se consideran estadísticos
significativos?</em></p>
<pre class="r"><code>data %&gt;%
  summarise(mean(sostenibilidad, na.rm=T))</code></pre>
<pre><code>##   mean(sostenibilidad, na.rm = T)
## 1                        35.97215</code></pre>
<pre class="r"><code>predict(modelo1,data.frame(sostenibilidad=35.97215))</code></pre>
<pre><code>##        1 
## 33.88476</code></pre>
</div>
<div id="regresión-múltiple" class="section level2">
<h2>Regresión múltiple</h2>
<p><em>Crea un modelo para predecir la satisfacción con aspectos que
influyen en la calidad de vida considerando la satisfacción con aspectos
del medio ambiente y la pertenencia al NSE C (NSE)?</em></p>
<ol style="list-style-type: decimal">
<li>Fastdummies</li>
</ol>
<pre class="r"><code>data = dummy_cols(data, select_columns = &quot;NSE&quot;)

#Cambia el nombre de la columna de interés para mayor facilidad
data = rename(data,c(&quot;NSE_C&quot;=`NSE_NSE C`)) </code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Realizar el modelo</li>
</ol>
<pre class="r"><code>modelo2 = lm(satisfaccion ~ sostenibilidad + NSE_C, data = data)
summary(modelo2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = satisfaccion ~ sostenibilidad + NSE_C, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.318  -9.885   0.051   9.397  49.697 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     11.6918     1.0606  11.024   &lt;2e-16 ***
## sostenibilidad   0.5889     0.0233  25.279   &lt;2e-16 ***
## NSE_C            2.0370     0.9034   2.255   0.0244 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.95 on 951 degrees of freedom
##   (163 observations deleted due to missingness)
## Multiple R-squared:  0.4029, Adjusted R-squared:  0.4017 
## F-statistic: 320.9 on 2 and 951 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Interpretamos</li>
</ol>
<p>A. Validez del modelo: siendo el p-valor menor a 0.05, es posible
afirmar que el modelo es válido.</p>
<p>B. Aporte de las variables independientes al modelo: Puede observarse
que tanto la satisfacción con aspectos relacionados al medio ambiente
como la pertenencia al NSE C de una persona contribuyen a la explicación
de la variabilidad con la satisfacción de los aspectos que influyen en
la calidad de vida de la ciudad.</p>
<p>C. Explicación del modelo: el modelo indica que aproximadamente el
40.17% (Adjusted R-squared) de la variabilidad en la satisfacción con
aspectos que influyen en la calidad de vida de la ciudad puede ser
explicada por la satisfacción que tiene con aspectos relacionados al
medio ambiente y la pertenecia al NSE C.</p>
<p>*Representa la cantidad de variabilidad en los valores de Y que es
capturada por el modelo de regresión. Cuanto más cercano esté el valor a
1, mayor será la proporción de la variabilidad explicada por el
modelo.</p>
<p>D. Identificación e interpretación de la constante/intersección y la
pendiente/coeficiente: - Constante/ intersección: 11.6918 - Pendiente/
coeficiente de la variable sostenibilidad: 0.5889 - Pendiente/
coeficiente de NSE C: 2.0370</p>
<p>De ese modo, es posible afirmar que si la satisfación con aspectos
del medio ambiente es 0 y el NSE no es C, el valor de la satisfación con
aspectos que influyen en la calidad de vida es 11.6918, mientras que por
cada punto adicional en el indicador de sostenibilidad, la satisfacción
con aspectos que influyen en la calidad de vida aumenta en 0.5889.</p>
<p>Adicionalmente, el pertenecer al NSE C está asociado con un aumento
en indicador de satisfacción con aspectos que influyen en la calidad de
vida en 2.0370 a comparación con aquellos que no pertenezcan a este
nivel socioeconómico.</p>
<p>E. Ecuación de la recta:</p>
<p>Y = 11.6918 + 0.5889(X1) + 2.0370(X2)</p>
<p>F. Predecir <em>¿Cuál será la satisfacción con aspectos que influyen
en la calidad de vida de la ciudad si se consideran estadísticos
significativos y la no pertenencia al NSE C?</em></p>
<pre class="r"><code>data %&gt;%
  summarise(mean(sostenibilidad, na.rm=T))</code></pre>
<pre><code>##   mean(sostenibilidad, na.rm = T)
## 1                        35.97215</code></pre>
<pre class="r"><code>predict(modelo2, data.frame(sostenibilidad = 35.97215, NSE_C = 0))</code></pre>
<pre><code>##        1 
## 32.87482</code></pre>
<p>G. ¿Qué variable aporta más?</p>
<pre class="r"><code>summ(modelo2, scale=T)</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Observations
</td>
<td style="text-align:right;">
954 (163 missing obs. deleted)
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Dependent variable
</td>
<td style="text-align:right;">
satisfaccion
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Type
</td>
<td style="text-align:right;">
OLS linear regression
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
F(2,951)
</td>
<td style="text-align:right;">
320.86
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
R²
</td>
<td style="text-align:right;">
0.40
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Adj. R²
</td>
<td style="text-align:right;">
0.40
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
S.E.
</th>
<th style="text-align:right;">
t val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
32.87
</td>
<td style="text-align:right;">
0.64
</td>
<td style="text-align:right;">
51.69
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
sostenibilidad
</td>
<td style="text-align:right;">
11.42
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
25.28
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
NSE_C
</td>
<td style="text-align:right;">
2.04
</td>
<td style="text-align:right;">
0.90
</td>
<td style="text-align:right;">
2.25
</td>
<td style="text-align:right;">
0.02
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS; Continuous predictors are
mean-centered and scaled by 1 s.d.
</td>
</tr>
</tfoot>
</table>
<p>Se puede observar que el indicador de satisfacción con aspectos
relacionados con el medio ambiente tiene un mayor impacto que la
pertenecia al nivel socioeconómico C</p>
<pre class="r"><code>plot_summs(modelo2, scale = T)</code></pre>
<p><img src="pd11_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
