<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Práctica dirigida 3</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas Estadística_1</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="intro.html">Introducción</a>
</li>
<li>
  <a href="basico.html">Procedimientos básicos</a>
</li>
<li>
  <a href="pd1.html">Práctica 1</a>
</li>
<li>
  <a href="pd2.html">Práctica 2</a>
</li>
<li>
  <a href="Pd3.html">Práctica 3</a>
</li>
<li>
  <a href="pd4.html">Práctica 4</a>
</li>
<li>
  <a href="pd5.html">Práctica 5</a>
</li>
<li>
  <a href="pd6.html">Práctica 6</a>
</li>
<li>
  <a href="pd7.html">Práctica 7</a>
</li>
<li>
  <a href="pd8.html">Práctica 8</a>
</li>
<li>
  <a href="pd9.html">Práctica 9</a>
</li>
<li>
  <a href="pd10.html">Práctica 10</a>
</li>
<li>
  <a href="pd11.html">Práctica 11</a>
</li>
<li>
  <a href="pd12.html">Práctica 12</a>
</li>
<li>
  <a href="pd13.html">Práctica 13</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="https://github.com/arturomaldonado/PracticasPOL278">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Práctica dirigida 3</h1>

</div>


<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" /></p>
<p>FACULTAD DE CIENCIAS SOCIALES - PUCP<br></p>
<p>Curso: POL 278 - Estadística para el análisis político 1 | Semestre
2023 - 1 <br></p>
<div id="intervalos-de-confianza" class="section level1">
<h1><strong>1.Intervalos de confianza</strong></h1>
<p>Primero, recordemos que en esta sesión nos estamos adentrando en la
estadística inferencial. El objetivo de esta es determinar una
aproximación del parámetro poblacional a partir de la data de una
muestra representativa.</p>
<p>Revisemos algunos conceptos:</p>
<ul>
<li><p><strong>Estimador puntual:</strong> un número que es nuestra
predicción del parámetro</p></li>
<li><p><strong>Intervalo de confianza:</strong> un intervalo de números
basado en la distribución de la data observada de la muestra dentro de
la cual se cree que estaría el parámetro poblacional.</p>
<p><em>IC = estimador puntual +-/margen de error</em></p></li>
<li><p><strong>Nivel de confianza:</strong> es la probabilidad de que el
parámetro se encuentre en ese intervalo.</p></li>
<li><p><strong>Margen de error:</strong> mide qué tan precisa es la
estimación del parámetro.</p></li>
<li><p><strong>Error de muestreo:</strong> diferencia entre el valor
calculado de un estadístico y valor real de un parámetro de la
población.</p></li>
</ul>
<p><img src="IC.png" width="50%" style="display: block; margin: auto;" /></p>
<div id="importancia" class="section level3">
<h3>Importancia</h3>
<p>Los intervalos de confianza ofrecen una manera de estimar, con alta
probabilidad, un rango de valores en el que se encuentra el parámetro de
una determinada variable. Además, este describe la variabilidiad entre
la medida obtenida en un estudio y la medida real de la población (valor
real). Un intervalo de confianza de 90%/95%/99% nos indica que dentro
del rango dado se encuentra el valor real de un parámetro con
90%/95%/99% de certeza. Recordemos también que existe una relación
inversa entre la amplitud del intervalo de confianza y el tamaño
muestral. Gracias al intervalo de confianza podemos determinar si la
estimación es representativa de la población.</p>
</div>
<div id="sobre-el-nivel-de-confianza" class="section level3">
<h3>Sobre el nivel de confianza…</h3>
<p>Si tenemos un nivel de confianza de 95%, quiere decir que si
realizamos 100 veces el mismo procedimiento de muestreo y calculamos los
estadísticos de interés, 95 veces obtendremos los resultados en el
intervalo calculado. Los mismo ocurriría si realizamos el cáldulo con un
99% de confianza. Al momento de decidir el nivel de confianza debemos
tener presente una regla: a mayor nivel de confianza, menor será la
precisión ya que el intervalo es más amplio.</p>
</div>
</div>
<div id="intervalos-de-confianza-para-una-media" class="section level1">
<h1><strong>2.Intervalos de confianza para una media</strong></h1>
<p>Carguemos la data <em>ENADES2022.dta</em></p>
<p>La Encuesta Nacional de Percepción de Desigualdades o ENADES ha sido
elaborada por el Instituto de Estudios Peruanos (IEP) y Oxfam. Como lo
indica su nombre, este estudio se enfoca en analizar la percepción de
diferentes formas de desigualdad en el país. Esta incluye indicadores
que permiten medir la magnitud de brechas sociales y políticas:
diferencias de género, clase y relaciones étnico raciales, y dimensiones
subjetivas de desigualdad y sus vínculos con orientaciones políticas. En
este caso, nuestra unidad de análisis sería cada persona que completó la
encuesta.</p>
<pre class="r"><code>library(rio) #Convocamos el paquete   
data=import(&quot;ENADES-2022.dta&quot;) </code></pre>
<p>Recordemos la fórmula para hallar el intervalo de confianza para una
media es</p>
<p><img src="ICmedia.png" width="50%" style="display: block; margin: auto;" /></p>
<p><em>Hallemos el intervalo de confianza para la media de la variable
“ABros4”.</em></p>
<p>El enunciado de la pregunta es indicar en una escala de 1 a 10, donde
1 significa “Muy en desacuerdo” y 10 significa “Muy de acuerdo, ¿qué tan
de acuerdo o en desacuerdo se encuentra con la afirmación”El Estado
peruano debe implementar políticas firmes para reducir la desigualdad de
ingresos entre ricos y pobres”.</p>
<pre class="r"><code>class(data$ABros4) #Revisemos que nuestra variale esté bien clasificada</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p><strong>ciMean</strong>, del paquete <strong>lsr</strong>, es la
función que calcula el intervalo de confianza de una media.</p>
<pre class="r"><code>library(lsr)
ic_media = ciMean(data$ABros4, na.rm = TRUE) #con el último argumento indicamos no tomar en consideracion los valores perdidos (NA)

ic_media</code></pre>
<pre><code>##         2.5%    97.5%
## [1,] 7.54425 7.828429</code></pre>
<p>Nuestra media poblacional se encuentra entre 7.54 y 7.82. Esto quiere
decir que la estimación del intervalo indica que tenemos un 95% de
certeza de que el valor poblacional del nivel de acuerdo con la
afirmación “El Estado peruano debe implementar políticas firmes para
reducir la desigualdad de ingresos entre ricos y pobres” se encuentra
entre 7.5 y 7.8.</p>
</div>
<div id="intervalos-de-confianza-para-una-proporción"
class="section level1">
<h1><strong>3.Intervalos de confianza para una proporción</strong></h1>
<p>Tengamos en consideración que para poder hallar el intervalo de
confianza para una proporción debemos determinar nuestro caso de éxtio.
Asimismo, para hallar el intervalo de confianza para una proporción
nuestra variable debe ser categórica y debe representar una variable
dicotómica; es decir, una variable con solo dos categorías posibles:
votó/no votó; sí/no, etc.</p>
<p>Recordemos la fórmula para hallar el intervalo de confianza para una
proporción</p>
<p><img src="ICprop.png" width="50%" style="display: block; margin: auto;" /></p>
<p><em>Hallemos el intervalo de confianza para la proporción de las
personas que opinan que hay mucha desigualdad económica en el
Perú.</em></p>
<p>Para ello trabajaremos con la variable P04: ¿Qué tal desigual crees
que es el Perú económicamente? Las alternativas van del 1 al 4, donde 1
es mucho y 4 nada.</p>
<p>Un paso previo es asegurarnos que nuestra variable es dicotómica y
tener presente nuestro caso de éxito. En este caso, nuestra variable
tiene cuatro posibles valores, es por eso que debemos recodificar la
variable de tal modo que el valor 1 se quede como 1, y todos los demás
valores se conviertan en 0.</p>
<pre class="r"><code>class(data$p04)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>data$p04=as.factor(data$p04)
table(data$p04) #Asegurémonos de los valores</code></pre>
<pre><code>## 
##   1   2   3   4 
## 868 265 275  85</code></pre>
<p>Para recodificar podemos hacer uso del comando recode, que es parte
del dplyr/tidyverse.</p>
<pre class="r"><code>library(tidyverse)

data = data %&gt;%
  mutate(p04_1=recode(p04, &#39;1&#39; = &#39;1&#39;,  .default = &#39;0&#39;))

table(data$p04_1) #Confirmemos que se realizó correctamente la recategorización</code></pre>
<pre><code>## 
##   1   0 
## 868 625</code></pre>
<p>Agreguemos etiquetas a nuestros valores</p>
<pre class="r"><code>data$p04_1=factor(data$p04_1,
                levels = levels(data$p04_1),
                labels = c(&quot;Mucho&quot;,&quot;Algo/Poco/Nada&quot;),
                ordered = F)</code></pre>
<p>Para poder encontrar el intervalo de confianza para la proporción de
personas que opinan que hay mucha desigualdad en Perú, necesitamos tener
muy claro la frecuencia de nuestro caso de éxtio y del total de
casos.</p>
<pre class="r"><code>table(data$p04_1)#realizamos una tabla de frecuencias</code></pre>
<pre><code>## 
##          Mucho Algo/Poco/Nada 
##            868            625</code></pre>
<pre class="r"><code>x = 868 #almacenamos en &quot;x&quot; la frecuencia de nuestro caso de éxito
n = 868 + 625 #almacenamos en &quot;n&quot; el total de casos</code></pre>
<p>Hallamos el invervalo de confianza para una proporción con el comando
<strong>prop.test</strong></p>
<pre class="r"><code>ic_prop = prop.test(x,n)
ic_prop #llamamos a ic_prop para visualizar los resultados</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  x out of n, null probability 0.5
## X-squared = 39.226, df = 1, p-value = 3.775e-10
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.5558413 0.6064950
## sample estimates:
##         p 
## 0.5813798</code></pre>
<p>Esto quiere decir que tenemos un 95% de certeza de que, en la
población, el porcentaje de personas que considera que existe mucha
desigualdad en el Perú oscila entre el 55.6% y 60.6% .</p>
</div>
<div id="intervalo-de-confianza-de-una-media-según-grupo"
class="section level1">
<h1><strong>3.Intervalo de confianza de una media según
grupo</strong></h1>
<p>Hallemos el intervalo de confianza para el nivel de acuerdo con que
“El Estado peruano debe implementar políticas firmes para reducir la
desigualdad de ingresos entre ricos y pobres” según si considera que
existe mucha desigualdad o no en el Perú. Para ello usaremos el comando
<strong>group.CI</strong> del paquete Rmisc</p>
<pre class="r"><code>library(Rmisc)
ic_grupo = group.CI(ABros4~p04_1,data)
ic_grupo</code></pre>
<pre><code>##            p04_1 ABros4.upper ABros4.mean ABros4.lower
## 1          Mucho     8.142751    7.969732     7.796714
## 2 Algo/Poco/Nada     7.576645    7.334951     7.093258</code></pre>
<p>Según nuestra tabla, podemos afirmar que hay un 95% de probabilidad
de que a nivel poblacional la media del grupo que considera que hay
mucha desigualdad en el Perú está de acuerdo en mayor medida con que el
Estado debe implementar políticas firmes para reducir la desigualdad, a
comparación de lo que no se consideran que hay mucha desigualdad.</p>
<p>Grafiquemos nuestros resultados.</p>
<pre class="r"><code>ggplot(ic_grupo, aes(x= p04_1, y =ABros4.mean)) +
  geom_errorbar(aes(ymin=ABros4.lower, ymax=ABros4.upper), width = 0.2)+
   geom_text(aes(label=paste(round(ABros4.mean, 2))), size=4)+
  xlab(&quot;Considera que hay ... desigualdad en el Perú&quot;) + ylab(&quot;Nivel de acuerdo con que se necesitan \n políticas firmes para reducir brechas&quot;)+
  ylim(7, 8.5)</code></pre>
<p><img src="Pd3_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>¿Qué podemos extraer del gráfico?</p>
<div id="ejercicio" class="section level2">
<h2>Ejercicio</h2>
<p>Trabajemos con la variable p03_1: nivel de acuerdo con la frase “En
el Perú todos tienen iguales oportunidades para salir de la pobreza”, va
del 1 (muy en desacuerdo) al 10 (muy de acuerdo)</p>
<ul>
<li><p>¿Cuál es el intervalo de confianza de la media de la
variable?</p></li>
<li><p>¿ Cuál es la diferencia del intervalo de confianza de la media
según región natural? (variable region)</p></li>
</ul>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
