<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Práctica dirigida 3</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas Estadística_1</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="intro.html">Introducción</a>
</li>
<li>
  <a href="basico.html">Procedimientos básicos</a>
</li>
<li>
  <a href="pd1.html">Práctica 1</a>
</li>
<li>
  <a href="pd2.html">Práctica 2</a>
</li>
<li>
  <a href="Pd3.html">Práctica 3</a>
</li>
<li>
  <a href="pd4.html">Práctica 4</a>
</li>
<li>
  <a href="pd5.html">Práctica 5</a>
</li>
<li>
  <a href="pd6.html">Práctica 6</a>
</li>
<li>
  <a href="pd7.html">Práctica 7</a>
</li>
<li>
  <a href="pd8.html">Práctica 8</a>
</li>
<li>
  <a href="pd9.html">Práctica 9</a>
</li>
<li>
  <a href="pd10.html">Práctica 10</a>
</li>
<li>
  <a href="pd11.html">Práctica 11</a>
</li>
<li>
  <a href="pd12.html">Práctica 12</a>
</li>
<li>
  <a href="pd13.html">Práctica 13</a>
</li>
<li>
  <a href="FAQ.html">FAQ</a>
</li>
<li>
  <a href="https://github.com/arturomaldonado/PracticasPOL278">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Práctica dirigida 3</h1>

</div>


<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" /></p>
<p><strong>FACULTAD DE CIENCIAS SOCIALES - PUCP</strong><br></p>
<div
id="curso-pol-278---estadística-para-el-análisis-político-1-semestre-2024---1"
class="section level2">
<h2>Curso: POL 278 - Estadística para el análisis político 1 | Semestre
2024 - 1 <br></h2>
</div>
<div id="intervalos-de-confianza" class="section level1">
<h1><strong>1.Intervalos de confianza</strong></h1>
<p>Con este tema, comenzaremos a enfocarnos en la estadística
inferencial. El objetivo de esta es determinar una aproximación del
parámetro poblacional a partir de la data de una muestra
representativa.</p>
<p>Revisemos algunos conceptos:</p>
<ul>
<li><p><strong>Estimador puntual:</strong> un número que es nuestra
predicción del parámetro</p></li>
<li><p><strong>Intervalo de confianza:</strong> un intervalo de números
basado en la distribución de la data observada de la muestra dentro de
la cual se cree que estaría el parámetro poblacional.</p>
<p><em>IC = estimador puntual +-/margen de error</em></p></li>
<li><p><strong>Nivel de confianza:</strong> es la probabilidad de que el
parámetro se encuentre en ese intervalo.</p></li>
<li><p><strong>Margen de error:</strong> mide qué tan precisa es la
estimación del parámetro.</p></li>
<li><p><strong>Error de muestreo:</strong> diferencia entre el valor
calculado de un estadístico y valor real de un parámetro de la
población.</p></li>
</ul>
<p><img src="IC.png" width="50%" style="display: block; margin: auto;" /></p>
<div id="conceptualización-e-importancia" class="section level3">
<h3>Conceptualización e Importancia</h3>
<ul>
<li>Los intervalos de confianza ofrecen una manera de estimar, con alta
probabilidad, un rango de valores en el que se encuentra el valor
poblacional (o parámetro) de una determinada variable.</li>
<li>El intervalo de confianza describe la variabilidad entre la medida
obtenida en un estudio y la medida real de la población (el valor
real).</li>
<li>Un intervalo de confianza de 90%/95%/99% nos indica que dentro del
rango dado se encuentra el valor real de un parámetro con 90%/95%/99% de
certeza.</li>
<li>Existe una relación inversa entre la amplitud del IC y el tamaño
muestral: mientras más pequeño es el n, más amplio es el IC. A mayor n,
el IC es más estrecho.</li>
<li>Gracias al IC podemos determinar si la estimación es representativa
de la población.</li>
</ul>
</div>
<div id="sobre-el-nivel-de-confianza" class="section level3">
<h3>Sobre el nivel de confianza…</h3>
<p>Si tenemos un nivel de confianza de 95%, quiere decir que si
realizamos 100 veces el mismo procedimiento de muestreo y calculamos los
estadísticos de interés, 95 veces obtendremos los resultados en el
intervalo calculado. Los mismo ocurriría si realizamos el cálculo con un
99% de confianza. Al momento de decidir el nivel de confianza debemos
tener presente una regla: a mayor nivel de confianza, menor será la
precisión ya que el intervalo es más amplio.</p>
<div
id="la-data-de-hoy-e-government-survey-2022-the-future-of-digital-government"
class="section level4">
<h4><strong>La data de hoy: E-Government Survey 2022: The Future of
Digital Government</strong></h4>
<p>La Encuesta de las Naciones Unidas sobre Gobierno Electrónico se ha
publicado cada dos años por el Departamento de Asuntos Económicos y
Sociales de las Naciones Unidas desde 2001. La Encuesta evalúa el estado
de desarrollo del gobierno electrónico de todos los Estados miembros de
las Naciones Unidas y, durante este tiempo, ha establecido un conjunto
de datos y análisis exhaustivos.</p>
<p>La evaluación mide el rendimiento del gobierno electrónico de los
países en relación con los demás, en lugar de ser una medición absoluta.
Reconoce que cada país debe decidir el nivel y la extensión de sus
iniciativas de gobierno electrónico de acuerdo con sus propias
prioridades nacionales de desarrollo y para lograr los Objetivos de
Desarrollo Sostenible. La Encuesta sirve como una herramienta de
referencia y desarrollo para que los países aprendan entre sí,
identifiquen áreas de fortaleza y desafíos en el gobierno electrónico y
moldeen sus políticas y estrategias. También tiene como objetivo
facilitar e informar las discusiones de los órganos
intergubernamentales, incluida la Asamblea General de las Naciones
Unidas, el Consejo Económico y Social y el Foro Político de Alto
Nivel.</p>
<p><img src="PD3_egov22.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Carguemos la data <em>egov2022.xlsx</em></p>
<pre class="r"><code>library(dplyr) #Para summarise, mutate, group_by...
library(rio) #para importar la data
library(lsr) #para ciMean
library(ggplot2) #para graficar
data=import(&quot;egov2022.xlsx&quot;) </code></pre>
<table>
<colgroup>
<col width="26%" />
<col width="73%" />
</colgroup>
<thead>
<tr class="header">
<th>Nombre</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pais</td>
<td>Nombre del país</td>
</tr>
<tr class="even">
<td>E_gov</td>
<td>Indicador de gobernanza digital (0-100)</td>
</tr>
<tr class="odd">
<td>E_part</td>
<td>Transparencia y acceso a la información, participación ciudadana en
línea (0 - 100)</td>
</tr>
<tr class="even">
<td>Online_service</td>
<td>Servicios en línea otorgado por el Estado</td>
</tr>
<tr class="odd">
<td>Human_cap</td>
<td>Miembros del Estado especializados en el tema</td>
</tr>
<tr class="even">
<td>Tele_infra</td>
<td>Índice de capacidad de redes de telecomunicaciones como acceso a
internet 5G</td>
</tr>
<tr class="odd">
<td>Region</td>
<td>Continente donde pertenece cada país</td>
</tr>
</tbody>
</table>
</div>
</div>
<div
id="pregunta-cuál-es-el-estado-de-la-gobernanza-digital-de-los-países"
class="section level2">
<h2>Pregunta: ¿Cuál es el estado de la gobernanza digital de los
países?</h2>
</div>
<div id="intervalo-de-confianza-para-una-proporción"
class="section level2">
<h2><strong>1.1 Intervalo de confianza para una proporción</strong></h2>
<p>Tengamos en consideración que para poder hallar el intervalo de
confianza para una proporción debemos determinar nuestro caso de éxito.
Asimismo, para hallar el intervalo de confianza para una proporción
nuestra variable debe ser categórica y debe representar una variable
dicotómica; es decir, una variable con solo dos categorías posibles:
votó/no votó; sí/no, etc.</p>
<p>Recordemos la fórmula para hallar el intervalo de confianza para una
proporción</p>
<p><img src="ICprop.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Para este ejercicio responderemos a la pregunta:</p>
</div>
<div
id="qué-proporción-de-países-tienen-un-nivel-de-transparencia-y-participación-ciudadana-en-línea-alto"
class="section level2">
<h2>¿Qué proporción de países tienen un nivel de transparencia y
participación ciudadana en línea alto?</h2>
<p>Para ello, hallaremos el intervalo de confianza para la proporción de
países que tienen un nivel de transparencia y participación ciudadana en
línea es mayor a 70.</p>
<p>Según el diccionario de datos, la variable que mide la transparencia
y acceso a la información, participación ciudadana en línea (E_part) es
numérica. Necesitamos crear una nueva variable que sea dicotómica y que
tenga como punto de corte 70, la llamaremos “E_part_alto”. Es decir,
todos los países que tengan un valor en E_gov mayor a 70 será “Alto” y
los que no será “No alto”.</p>
<p>Lograremos esto con el comando ifelse. Este comando tiene 3
argumentos: condición, valor si se cumple la condición, valor cuando no
se cumple la condición. Veamos como se aplica a continuación:</p>
<pre class="r"><code>data = data %&gt;% 
  mutate(E_part_alto = ifelse(E_part &gt; 70, &quot;Alto&quot;,&quot;No alto&quot;))</code></pre>
<p>Ahora que hemos tenemos una variable dicotómica que indique el nivel
de transparencia y participación ciudadana en línea, podemos calcular el
intervalo para la proporción de países con ese indicador alto.</p>
<p>Debemos realizar una tabla de frecuencias, y luego de identificar el
n del caso de éxito y el total ingresamos los valores en el
prop.test.</p>
<ul>
<li>Tabla de frecuencias:</li>
</ul>
<p>Agrupando por “E_part_alto”, realizamos un conteo.</p>
<pre class="r"><code>  data %&gt;% 
  group_by(E_part_alto) %&gt;% 
  summarise(Freq=n())</code></pre>
<pre><code>## # A tibble: 2 × 2
##   E_part_alto  Freq
##   &lt;chr&gt;       &lt;int&gt;
## 1 Alto           36
## 2 No alto       145</code></pre>
<p>El número casos de éxito es <strong>36</strong> y el total es
<strong>36+145.</strong> Reemplacemos esos valores en el prop.test.
Primero indicamos los casos de éxito y luego el total de casos.</p>
<pre class="r"><code>ic_prop  = prop.test(36,181)
ic_prop #llamamos a ic_prop para visualizar los resultados</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  36 out of 181, null probability 0.5
## X-squared = 64.442, df = 1, p-value = 9.942e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.1448583 0.2660320
## sample estimates:
##        p 
## 0.198895</code></pre>
<p>Esto quiere decir que tenemos un 95% de certeza de que, en la
población, el porcentaje de países con un nivel alto de participación
ciudadana y transparencia online oscila entre 14.5% y 26.7%.</p>
</div>
<div id="intervalo-de-confianza-para-una-media" class="section level2">
<h2>1.2 Intervalo de confianza para una media</h2>
</div>
<div id="intervalo-de-confianza-para-una-media-según-grupo"
class="section level2">
<h2>1.3 Intervalo de confianza para una media según grupo</h2>
</div>
</div>
<div id="ejercicios" class="section level1">
<h1>Ejercicios:</h1>
<ol style="list-style-type: decimal">
<li><p>Halla el intervalo de confianza para la proporción de países que
cuentan un puntaje en servicios estatales (Online_service) bajo (menor a
25).</p>
<p><em>Hint:</em> Usar ifelse, cuando Online_service sea menor a 25 será
“Bajo”, cuando es mayor o igual será “No bajo”.</p></li>
<li><p>Crea la variable Region2. Cuando la region sea “Asia”, se
mantiene como “Asia”, todo lo demás (Africa, Americas, Europe, Oceania)
será “No Asia”. ¿Existe una diferencia en el indicador de
infraestructura en telecomunicaciones (Tele_infra) si el país está en
Asia?</p>
<p>Hint:</p></li>
<li><p>Realizar un gráfico de barras para la pregunta anterior</p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
