<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Práctica dirigida 4</title>

<script src="site_libs/header-attrs-2.21/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.0/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.0/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas Estadística_1</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="intro.html">Introducción</a>
</li>
<li>
  <a href="basico.html">Procedimientos básicos</a>
</li>
<li>
  <a href="pd1.html">Práctica 1</a>
</li>
<li>
  <a href="pd2.html">Práctica 2</a>
</li>
<li>
  <a href="pd3.html">Práctica 3</a>
</li>
<li>
  <a href="pd4.html">Práctica 4</a>
</li>
<li>
  <a href="pd5.html">Práctica 5</a>
</li>
<li>
  <a href="pd6.html">Práctica 6</a>
</li>
<li>
  <a href="pd7.html">Práctica 7</a>
</li>
<li>
  <a href="pd8.html">Práctica 8</a>
</li>
<li>
  <a href="pd9.html">Práctica 9</a>
</li>
<li>
  <a href="pd10.html">Práctica 10</a>
</li>
<li>
  <a href="pd11.html">Práctica 11</a>
</li>
<li>
  <a href="pd12.html">Práctica 12</a>
</li>
<li>
  <a href="pd13.html">Práctica 13</a>
</li>
<li>
  <a href="FAQ.html">FAQ</a>
</li>
<li>
  <a href="https://github.com/arturomaldonado/PracticasPOL278">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Práctica dirigida 4</h1>

</div>


<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" /></p>
<p><strong>FACULTAD DE CIENCIAS SOCIALES - PUCP</strong><br></p>
<div
id="curso-pol-278---estadística-para-el-análisis-político-1-semestre-2024---2"
class="section level2">
<h2>Curso: POL 278 - Estadística para el análisis político 1 | Semestre
2024 - 2 <br></h2>
</div>
<div id="intervalos-de-confianza" class="section level1">
<h1><strong>Intervalos de confianza</strong></h1>
<p>Con este tema, nos adentraremos en el estudio de la estadística
inferencial, cuyo objetivo es estimar y aproximar los parámetros
poblacionales basados en los datos obtenidos de una muestra
representativa. A través de este enfoque, podemos hacer generalizaciones
válidas sobre una población completa a partir de un subconjunto de
datos, permitiendo tomar decisiones y formular conclusiones
fundamentadas.</p>
<p>Revisemos algunos conceptos:</p>
<ul>
<li><p><strong>Estimador puntual:</strong> un número que es nuestra
predicción del parámetro</p></li>
<li><p><strong>Intervalo de confianza (IC):</strong> un intervalo de
números basado en la distribución de la data observada de la muestra
dentro de la cual se cree que estaría el parámetro poblacional.</p></li>
</ul>
<p><span class="math display">\[IC = \text{estimador puntual} \pm
\text{margen de error}\]</span></p>
<ul>
<li><p><strong>Nivel de confianza:</strong> es la probabilidad de que el
parámetro se encuentre en ese intervalo.</p></li>
<li><p><strong>Margen de error:</strong> mide qué tan precisa es la
estimación del parámetro.</p></li>
<li><p><strong>Error de muestreo:</strong> diferencia entre el valor
calculado de un estadístico y valor real de un parámetro de la
población.</p></li>
</ul>
<p><img src="IC.png" width="50%" style="display: block; margin: auto;" /></p>
<div id="conceptualización-e-importancia" class="section level3">
<h3>Conceptualización e Importancia</h3>
<ul>
<li>Los intervalos de confianza ofrecen una manera de estimar, con alta
probabilidad, un rango de valores en el que se encuentra el valor
poblacional (o parámetro) de una determinada variable.</li>
<li>El intervalo de confianza describe la variabilidad entre la medida
obtenida en un estudio y la medida real de la población (el valor
real).</li>
<li>Un intervalo de confianza de 90%/95%/99% nos indica que dentro del
rango dado se encuentra el valor real de un parámetro con 90%/95%/99% de
certeza.</li>
<li>Existe una relación inversa entre la amplitud del IC y el tamaño
muestral: mientras más pequeño es el n, más amplio es el IC. A mayor n,
el IC es más estrecho.</li>
<li>Gracias al IC podemos determinar si la estimación es representativa
de la población.</li>
</ul>
</div>
<div id="sobre-el-nivel-de-confianza" class="section level3">
<h3>Sobre el nivel de confianza</h3>
<p>Si tenemos un nivel de confianza de 95%, quiere decir que si
realizamos 100 veces el mismo procedimiento de muestreo y calculamos los
estadísticos de interés, 95 veces obtendremos los resultados en el
intervalo calculado. Los mismo ocurriría si realizamos el cálculo con un
99% de confianza. Al momento de decidir el nivel de confianza debemos
tener presente una regla: a mayor nivel de confianza, menor será la
precisión ya que el intervalo es más amplio.</p>
</div>
<div id="intervalos-de-confianza-para-una-proporción"
class="section level3">
<h3><strong>1.Intervalos de confianza para una proporción</strong></h3>
<p>Tengamos en consideración que para poder hallar el intervalo de
confianza para una proporción debemos determinar nuestro caso de éxito.
Asimismo, para hallar el intervalo de confianza para una proporción
nuestra variable debe ser categórica y debe representar una variable
dicotómica; es decir, una variable con solo dos categorías posibles:
votó/no votó; sí/no, etc.</p>
<p>Recordemos la fórmula para hallar el intervalo de confianza para una
proporción</p>
<p><img src="ICprop.png" width="70%" style="display: block; margin: auto;" />
<strong>Ejemplo práctico:</strong></p>
<p><img src="food.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Una empresa muy conocida de comida para gatos llamada <em>Furbys</em>
desea realizar un relanzamiento de marca. Para ello crean el eslogan “8
de cada 10 gatos prefieren Furbys”. Sin embargo, debido a un reclamo de
los alumnos del curso de Estadística, esta vez la empresa decide
realizar el sustento de su eslogan.</p>
<pre class="r"><code>library(rio)
cats=import(&quot;cats.xlsx&quot;)
str(cats)</code></pre>
<pre><code>## &#39;data.frame&#39;:    400 obs. of  3 variables:
##  $ Furbys: chr  &quot;no&quot; &quot;sí&quot; &quot;sí&quot; &quot;sí&quot; ...
##  $ Edad  : num  15 14 15 3 13 3 7 2 4 11 ...
##  $ Color : chr  &quot;Marrón&quot; &quot;Negro&quot; &quot;Negro&quot; &quot;Negro&quot; ...</code></pre>
<pre class="r"><code>table(cats$Furbys)</code></pre>
<pre><code>## 
##  no  sí 
## 152 248</code></pre>
<p>Formateo la variable <em>Furbys</em></p>
<pre class="r"><code>library(dplyr)
cats = cats %&gt;%
  mutate(Furbys = factor(Furbys, levels = c(&quot;sí&quot;, &quot;no&quot;)))
str(cats) #corroboro que ya cuento con mi categórica</code></pre>
<pre><code>## &#39;data.frame&#39;:    400 obs. of  3 variables:
##  $ Furbys: Factor w/ 2 levels &quot;sí&quot;,&quot;no&quot;: 2 1 1 1 2 1 2 2 1 1 ...
##  $ Edad  : num  15 14 15 3 13 3 7 2 4 11 ...
##  $ Color : chr  &quot;Marrón&quot; &quot;Negro&quot; &quot;Negro&quot; &quot;Negro&quot; ...</code></pre>
<pre class="r"><code>tablaCats &lt;- cats %&gt;%
  group_by(Furbys) %&gt;%
  summarise(N = n(), .groups = &quot;drop&quot;) %&gt;%
  mutate(total = sum(N),
         Porcentaje = N / total * 100)
tablaCats</code></pre>
<pre><code>## # A tibble: 2 × 4
##   Furbys     N total Porcentaje
##   &lt;fct&gt;  &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
## 1 sí       248   400         62
## 2 no       152   400         38</code></pre>
<pre class="r"><code>prop.test(248,400) #caso de éxito y total</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  248 out of 400, null probability 0.5
## X-squared = 22.562, df = 1, p-value = 2.034e-06
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.5702368 0.6674206
## sample estimates:
##    p 
## 0.62</code></pre>
<p>Con base en los resultados del test de proporciones para una muestra
de 400 gatos, se estima que la proporción de gatos que prefieren la
marca de comida <em>Furbys</em> está entre el 57.02% y el 66.74%, con un
intervalo de confianza del 95%. Esto significa que, si se tomaran
múltiples muestras aleatorias de la misma población, en aproximadamente
el 95% de las ocasiones la proporción verdadera de gatos que prefieren
<em>Furbys</em> caería dentro de este rango.</p>
<p>La proporción observada en la muestra es del 62%, lo que sugiere que
6 de cada 10 gatos prefieren <em>Furbys</em>. En consecuencia, se puede
afirmar con evidencia estadística que una mayoría de gatos prefiere esta
marca.</p>
<p>Si se deseara utilizar este resultado como base para una campaña
publicitaria, una frase como “6 de cada 10 gatos prefieren Furbys” sería
un eslogan adecuado, sustentado en los datos obtenidos.</p>
</div>
<div id="intervalos-de-confianza-para-una-media" class="section level3">
<h3><strong>2.Intervalos de confianza para una media</strong></h3>
<p>Recordemos la fórmula para hallar el intervalo de confianza para una
media es:</p>
<p><img src="ICmedia.png" width="70%" style="display: block; margin: auto;" />
- <strong>Puntuación Z:</strong> Se ha considerado 1.96 dado que es lo
que corresponde al considerar el nivel de confianza de 95% en una
distribución normal.</p>
<p><span class="math display">\[IC = \bar{X} \pm 1.96 \times
\frac{s}{\sqrt{n}}\]</span></p>
</div>
<div id="intervalo-de-confianza-de-una-media-según-grupo"
class="section level3">
<h3><strong>3.Intervalo de confianza de una media según
grupo</strong></h3>
<p>El análisis de medias por grupos mediante intervalos de confianza
(IC) es una herramienta fundamental en la inferencia estadística, ya que
permite estimar el rango en el que es probable que se encuentre la media
poblacional de cada grupo, con un determinado nivel de confianza, como
el 95%. Este enfoque es útil cuando se quiere comparar subgrupos dentro
de una población, ya sea por género, nivel socioeconómico, ubicación
geográfica, entre otros.</p>
<p>Un aspecto clave del análisis con intervalos de confianza es observar
si los intervalos de los grupos se solapan o no:</p>
<ul>
<li><p>Si los intervalos no se cruzan, se puede inferir que existe una
diferencia significativa entre las medias de los grupos.</p></li>
<li><p>Si los intervalos se solapan, no podemos afirmar con certeza que
las medias sean significativamente diferentes, lo que sugiere que las
diferencias observadas podrían deberse al azar.</p></li>
</ul>
</div>
</div>
<div id="prueba-t" class="section level1">
<h1><strong>Prueba T</strong></h1>
<p>Generalmente, cuando queremos comparar dos grupos centramos nuestra
atención en el promedio de cada uno. Sin embargo, el hecho de que los
promedios sean distintos no supone, necesariamente, que existe una
diferencia <strong>estadísticamente significativa</strong>.</p>
<p>Para saber si la diferencia observada entre las medias de dos grupos
es o no significativa se emplean métodos paramétricos como el de
Z-scores o la distribución T-student. Estas técnicas calculan los
intervalos de confianza de cada grupo y concluyen si existe una
diferencia <em>real</em> entre las medias.</p>
<p>La prueba T compara la media de una variable numérica para dos grupos
o categorías de una variable nominal u ordinal. Los grupos que forman la
variable nominal/ordinal tienen que ser independientes. Es decir, cada
observación debe pertenecer a un grupo o al otro, pero
<strong>no</strong> a ambos.</p>
<p><strong>Ejemplo práctico:</strong></p>
<p>¿Existe una diferencia estadísticamente significativa entre el ataque
de los pokemon de tipo agua y tipo fuego?</p>
<pre class="r"><code>library(pokemon)
library(magick)
url1&lt;- pokemon %&gt;%
  filter(pokemon == &quot;charmander&quot;) %&gt;%
  pull(url_image)

url2 &lt;- pokemon %&gt;%
  filter(pokemon == &quot;squirtle&quot;) %&gt;%
  pull(url_image)

plot (image_append(c(image_read(url1), image_read(url2))))</code></pre>
<p><img src="pd4_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>names(pokemon)</code></pre>
<pre><code>##  [1] &quot;id&quot;              &quot;pokemon&quot;         &quot;species_id&quot;      &quot;height&quot;         
##  [5] &quot;weight&quot;          &quot;base_experience&quot; &quot;type_1&quot;          &quot;type_2&quot;         
##  [9] &quot;hp&quot;              &quot;attack&quot;          &quot;defense&quot;         &quot;special_attack&quot; 
## [13] &quot;special_defense&quot; &quot;speed&quot;           &quot;color_1&quot;         &quot;color_2&quot;        
## [17] &quot;color_f&quot;         &quot;egg_group_1&quot;     &quot;egg_group_2&quot;     &quot;url_icon&quot;       
## [21] &quot;generation_id&quot;   &quot;url_image&quot;</code></pre>
<pre class="r"><code>table(pokemon$type_1)</code></pre>
<pre><code>## 
##      bug     dark   dragon electric    fairy fighting     fire   flying 
##       79       37       39       61       19       31       59        4 
##    ghost    grass   ground      ice   normal   poison  psychic     rock 
##       40       84       36       29      111       35       64       65 
##    steel    water 
##       30      126</code></pre>
<pre class="r"><code>poke_filtrado = pokemon %&gt;%
  filter(type_1 %in% c(&quot;water&quot;, &quot;fire&quot;)) %&gt;%
  mutate(type_1 = factor(type_1))</code></pre>
<pre class="r"><code>str(poke_filtrado$type_1) #confirmo que está en factor</code></pre>
<pre><code>##  Factor w/ 2 levels &quot;fire&quot;,&quot;water&quot;: 1 1 1 2 2 2 1 1 2 2 ...</code></pre>
<p>Medias de ataque <em>attack</em></p>
<pre class="r"><code>pokeAttack = poke_filtrado %&gt;%
  group_by(type_1) %&gt;%
  summarize(Media = mean(attack, na.rm = T))
pokeAttack</code></pre>
<pre><code>## # A tibble: 2 × 2
##   type_1 Media
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 fire    84.3
## 2 water   74.7</code></pre>
<pre class="r"><code>pokeAttack[1,2] - pokeAttack[2,2]</code></pre>
<pre><code>##      Media
## 1 9.539952</code></pre>
<ul>
<li>La media de ataque de los Pokémon de tipo fuego es 84.25, mientras
que la media de ataque de los Pokémon de tipo agua es 74.71.</li>
<li>Esto sugiere que, en promedio, los Pokémon de tipo fuego tienden a
tener un ataque mayor que los Pokémon de tipo agua.</li>
</ul>
<p>Profundizamos en el análisis</p>
<pre class="r"><code>t.test(attack ~ type_1, data = poke_filtrado)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  attack by type_1
## t = 2.1583, df = 118.99, p-value = 0.03291
## alternative hypothesis: true difference in means between group fire and group water is not equal to 0
## 95 percent confidence interval:
##   0.7877524 18.2921507
## sample estimates:
##  mean in group fire mean in group water 
##            84.25424            74.71429</code></pre>
<ul>
<li>Como el p-value es 0.03291, lo que es menor que el nivel de
significancia comúnmente utilizado (α = 0.05). Esto indica que existe
una diferencia estadísticamente significativa entre las medias de los
ataques de los pokemon de tipo fuego y agua.</li>
<li>Por lo tanto, podemos <em>rechazar la hipótesis nula, que sostiene
que no</em> hay diferencia en los ataques entre los dos tipos.</li>
</ul>
<p>Conclusión: El análisis muestra que los pokemon de tipo fuego tienen
un ataque significativamente mayor que los de tipo agua, con una
diferencia promedio que varía entre aproximadamente 0.79 y 18.29 puntos
de ataque. Aunque la diferencia es estadísticamente significativa, la
magnitud de la diferencia puede no ser extremadamente grande en todos
los contextos, por lo que esta diferencia podría o no ser relevante
dependiendo de la aplicación práctica (por ejemplo, en batallas
competitivas o estrategias específicas). Sin embargo, en términos
generales, los pokemon de tipo fuego parecen ser más ofensivos que los
de tipo agua.</p>
</div>
<div id="dinámicas-del-uso-de-los-medios-de-transporte-en-lima"
class="section level1">
<h1><strong>🚙 Dinámicas del uso de los medios de transporte en
Lima</strong></h1>
<p>El crecimiento acelerado de Lima ha generado una creciente
preocupación sobre la calidad y eficiencia de los medios de transporte
en la ciudad. La congestión vehicular, la falta de infraestructura
adecuada y los largos tiempos de viaje afectan diariamente a millones de
limeños. En este contexto, el análisis de datos cuantitativos se vuelve
indispensable para entender el comportamiento de los usuarios,
identificar áreas críticas y diseñar soluciones efectivas. En ese
sentido en esta sesión responderemos a la siguiente pregunta:</p>
<style>
.custom-text {
  color: #00688B;
  font-family: Helvetica, sans-serif;
  text-align: center;
  font-weight: bold;
  font-size: 22px;
}
</style>
<div class="custom-text">
<p>¿Cuál es el estado del transporte en Lima según sus residentes?
🤔</p>
</div>
<p>Para acercarnos a responder la pregunta antes planteada se buscó
información relacionada al uso del transporte público en Lima. Por lo
tanto se eligió la encuesta de Lima Como Vamos, la cual es realizada a
ciudadanos de Lima y Callao con la finalidad de conocer su percepción
acerca de la movilidad, ambiente, seguridad ciudadana, espacios de
recreación, cultura y satisfacción con la ciudad. Pueden encontrar más
información acerca de esta base <a
href="https://www.limacomovamos.org/data/">aquí</a>.</p>
<p>Para esta sesión se usará una versión <em>subseteada</em> de años
anteriores que contiene las siguientes variables:</p>
<p><img src="pd4-diccionario.png" width="70%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>data=import(&quot;Limacomovamos-pd4.xlsx&quot;) </code></pre>
<hr>
<hr>
<h4 style="color: #00688B; text-align: center;">
<b>¿Cuál es el intervalo de confianza para la proporción de las personas
que están satisfechas con el transporte público en Lima?</b>
</h4>
<p>Para ello trabajaremos con la variable satis_transporte, que tiene
dos valores posibles: Satisfecho y no satisfecho.</p>
<p>Para poder encontrar el intervalo de confianza para la proporción de
ciudadanos de Lima y Callao satisfechos con el sistema de transporte,
necesitamos tener muy claro la frecuencia de nuestro caso de éxito y del
total de casos.</p>
<pre class="r"><code>tablaSatis = data %&gt;%
  filter(satis_transporte ==&quot;No satisfecho&quot; | satis_transporte == &quot;Satisfecho&quot;) %&gt;% #para evitar considerar NA y cambién el total
  count(Éxito = satis_transporte, name=&quot;N&quot;) %&gt;%
  mutate(total = sum(N), 
         Porcentaje = N / total * 100)
tablaSatis</code></pre>
<pre><code>##           Éxito    N total Porcentaje
## 1 No satisfecho 3544  3738  94.810059
## 2    Satisfecho  194  3738   5.189941</code></pre>
<p>Hallamos el invervalo de confianza para una proporción con el comando
<strong>prop.test</strong></p>
<pre class="r"><code>prop.test(194,3738) #casos de éxito y el total de casos.</code></pre>
<img src="pd4resultprop.png" width="70%" style="display: block; margin: auto;" />
Esto quiere decir que tenemos un 95% de certeza de que, en la población,
el porcentaje de ciudadanos de Lima y Callao satisfechos con el sistema
de transporte oscila entre el 4.5% y 5.9% .
<hr>
<hr>
<h4 style="color: #00688B; text-align: center;">
<b>¿Cuánto gastan los residentes de Lima en transporte?</b>
</h4>
<p><em>Hallemos el intervalo de confianza para la media de la variable
“PE10A”.</em></p>
<p>El enunciado de la pregunta es indicar “En promedio, ¿cuánto gasta su
hogar en Transporte?”.</p>
<pre class="r"><code>class(data$PE10A) #Revisemos que nuestra variable esté bien clasificada</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p><strong>ciMean</strong>, del paquete <strong>lsr</strong>, es la
función que calcula el intervalo de confianza de una media.</p>
<pre class="r"><code>library(lsr)
ic_media = ciMean(data$PE10A, na.rm = TRUE) #con el último argumento indicamos no tomar en consideracion los valores perdidos (NA)

ic_media</code></pre>
<pre><code>##          2.5%  97.5%
## [1,] 71.90169 90.764</code></pre>
<hr>
<hr>
<h4 style="color: #00688B; text-align: center;">
<b>¿De qué manera la zona de Lima en la que vive la persona se relaciona
con su gasto en transporte?</b>
</h4>
<p>Hallemos el intervalo de confianza para el gasto en trasporte en
promedio (PE10A) según estrato de lima (ESTRATOS_IOP).</p>
<p>Agreguemos etiquetas a la categórica</p>
<p><img src="pd4-estratos.png" width="70%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>data = data %&gt;% 
  mutate(ESTRATOS_IOP=factor(ESTRATOS_IOP, levels = (1:4), labels = c(&quot;Lima Centro&quot;,&quot;Lima Este&quot;,&quot;Lima Norte&quot;, &quot;Lima Sur&quot;)))</code></pre>
<p>Crearemos una tabla con la media, máximo y mínimo de la variable
PE10A, en base al grupo de ESTRATOS_IOP.</p>
<pre class="r"><code>ic_grupo = data %&gt;% 
  dplyr::group_by(ESTRATOS_IOP) %&gt;% 
  dplyr::summarise(Media = mean(PE10A, na.rm=T),
            min = ciMean(PE10A, na.rm=T)[1],
            max = ciMean(PE10A, na.rm=T)[2])
ic_grupo</code></pre>
<pre><code>## # A tibble: 4 × 4
##   ESTRATOS_IOP Media   min   max
##   &lt;fct&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Lima Centro  114.  101.  128. 
## 2 Lima Este     49.8  43.1  56.4
## 3 Lima Norte    95.0  65.0 125. 
## 4 Lima Sur      61.2  54.0  68.4</code></pre>
<p>Según nuestra tabla, podemos afirmar que hay un 95% de probabilidad
de que a nivel poblacional la media del grupo que los residentes de Lima
Centro y Lima Norte gastan más en transporte que los de Lima Este.</p>
<p>Grafiquemos nuestros resultados.</p>
<pre class="r"><code>library(ggplot2)

ggplot(ic_grupo, aes(x = ESTRATOS_IOP, y = Media)) +
  geom_bar(stat = &quot;identity&quot;, fill = &quot;#00688B&quot;, color = &quot;black&quot;) +
  geom_errorbar(aes(ymin = min, ymax = max), width = 0.2) +
  
  # Etiquetas de la media
  geom_text(aes(label = paste(round(Media, 2))), vjust = -1, size = 4) +
  
  # Etiquetas de los valores mínimos
  geom_text(aes(y = min, label = paste(&quot;min:&quot;, round(min, 2))), 
            vjust = 1.5, hjust = -0.2, size = 3, color = &quot;white&quot;) +
  
  # Etiquetas de los valores máximos
  geom_text(aes(y = max, label = paste(&quot;max:&quot;, round(max, 2))), 
            vjust = -0.5, hjust = -0.2, size = 3, color = &quot;#00688B&quot;) +
  
  xlab(&quot;Zona de Lima&quot;) + 
  ylab(&quot;Promedio del gasto en transporte&quot;) +
  ylim(0, 140) +
  theme_minimal()</code></pre>
<p><img src="pd4_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Con lo que muestra el gráfico, ¿cómo podemos complementar nuestra
interpretación anterior?</p>
<ul>
<li>Lima Centro gasta significativamente más que Lima Este y Lima Sur,
como lo indican los promedios y la falta de superposición considerable
entre los IC.</li>
<li>Lima Norte presenta un rango de gasto más amplio, lo que sugiere una
variabilidad mayor en el gasto de transporte dentro de esa zona.</li>
<li>Lima Este tiene un gasto más bajo y su intervalo de confianza no se
superpone con el de Lima Centro, lo que podría indicar diferencias
estadísticamente significativas entre estas dos zonas.</li>
</ul>
<h4 style="color: #00688B; text-align: center;">
<b>¿Existe una diferencia estadísticamente significativa entre el gasto
en transporte entre hombres y mujeres?</b>
</h4>
<p>Reviso mi df</p>
<pre class="r"><code>str(data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    3744 obs. of  7 variables:
##  $ SEXO            : num  2 2 2 1 2 1 1 1 2 2 ...
##  $ ESTRATOS_IOP    : Factor w/ 4 levels &quot;Lima Centro&quot;,..: 4 4 4 4 4 4 4 4 4 4 ...
##  $ NSE_IOP         : num  1 3 3 2 3 1 2 3 1 2 ...
##  $ satis_transporte: chr  &quot;Satisfecho&quot; &quot;No satisfecho&quot; &quot;No satisfecho&quot; &quot;No satisfecho&quot; ...
##  $ EG2OTRO         : num  NA NA NA NA 2 NA 63 50 NA NA ...
##  $ PE10A           : num  50 10 8 10 10 10 5 5 15 90 ...
##  $ Añoslima        : chr  NA NA NA NA ...</code></pre>
<pre class="r"><code>GSexo = data |&gt; 
  group_by(SEXO) |&gt;
  summarize(Media = mean(PE10A, na.rm = T))
GSexo</code></pre>
<pre><code>## # A tibble: 2 × 2
##    SEXO Media
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     1  87.1
## 2     2  76.0</code></pre>
<pre class="r"><code>GSexo[1,2] - GSexo[2,2]</code></pre>
<pre><code>##     Media
## 1 11.0681</code></pre>
<p>La diferencia es de aprox 11 soles. ¿Puedo afirmar que existe esta
diferencia en la población?</p>
<p>Para poder evaluar si existen o no diferencias poblacionales usaremos
t.test</p>
<pre class="r"><code>t.test(PE10A ~ SEXO, data = data)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  PE10A by SEXO
## t = 1.1169, df = 2160.1, p-value = 0.2642
## alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
## 95 percent confidence interval:
##  -8.365242 30.501440
## sample estimates:
## mean in group 1 mean in group 2 
##        87.09212        76.02402</code></pre>
<p>El valor p- value es 0.2642, que es mayor que el nivel típico de
significancia (generalmente α = 0.05). Un valor p alto sugiere que
<em>no</em> hay suficiente evidencia para rechazar la hipótesis nula. En
otras palabras, no podemos concluir que existe una diferencia
significativa entre las medias de los dos grupos (hombres y mujeres) con
respecto a la variable PE10A.</p>
</div>
<div id="ejercicios-para-casa" class="section level1">
<h1><strong>Ejercicios para casa</strong></h1>
<ol style="list-style-type: decimal">
<li>Calcular el intervalo de confianza de la media para los años que
llevan viviendo en Lima/Callao los residentes de Lima/Callao (EG2OTRO).
Interprete</li>
<li>Muestra un gráfico que los intervalos de confianza para la media de
EG2OTRO según nivel socio económico (NSE_IOP). Interprete</li>
<li>A partir de la variable EG2OTRO, se creó “Añoslima”. Que tiene dos
grupos “Más de 50 años” o “De 50 años a menos”. Calcula el intervalo de
confianza para la proporción de la variable “Añoslima” e
interpreta.</li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
