<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Práctica dirigida 5</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas Estadística_1</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="intro.html">Introducción</a>
</li>
<li>
  <a href="basico.html">Procedimientos básicos</a>
</li>
<li>
  <a href="pd1.html">Práctica 1</a>
</li>
<li>
  <a href="pd2.html">Práctica 2</a>
</li>
<li>
  <a href="Pd3.html">Práctica 3</a>
</li>
<li>
  <a href="pd4.html">Práctica 4</a>
</li>
<li>
  <a href="pd5.html">Práctica 5</a>
</li>
<li>
  <a href="pd6.html">Práctica 6</a>
</li>
<li>
  <a href="pd7.html">Práctica 7</a>
</li>
<li>
  <a href="pd8.html">Práctica 8</a>
</li>
<li>
  <a href="pd9.html">Práctica 9</a>
</li>
<li>
  <a href="pd10.html">Práctica 10</a>
</li>
<li>
  <a href="pd11.html">Práctica 11</a>
</li>
<li>
  <a href="pd12.html">Práctica 12</a>
</li>
<li>
  <a href="pd13.html">Práctica 13</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="https://github.com/arturomaldonado/PracticasPOL278">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Práctica dirigida 5</h1>

</div>


<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" /></p>
<div id="revisemos-lo-avanzado-sobre-estadística-inferencial"
class="section level1">
<h1><strong>Revisemos lo avanzado sobre estadística
inferencial</strong></h1>
<p>En esta sesión repasaremos lo revisado hasta el momento sobre
intervalos de confianza; así como también, recordaremos cómo crear un
indicador.</p>
<p>Hoy emplearemos algunas variables de la Encuesta Nacional de Docentes
ENDO 2020, realizada por el Ministerio de Educación. Esta encuesta
pretende recoger información acerca de los docentes y sus característica
sociodemográficas, económicas, sus percepciones, condiciones de trabajo,
y más. Si quieres conocer más acerca de esta encuesta ingresa al
siguiente <a href="#id_0">link</a>.</p>
<p>Llamemos a los paquetes que usaremos</p>
<pre class="r"><code>library(rio)
library(lsr)
library(dplyr)
library(ggplot2)</code></pre>
<p>Importemos la base de datos</p>
<pre class="r"><code>data=import(&quot;Endo-2021-sub.sav&quot;)</code></pre>
<p><img src="diccionario-endo.png" width="80%" /></p>
<p>Revisemos nuestra base</p>
<pre class="r"><code>str(data)
names(data)</code></pre>
</div>
<div id="intervalo-de-confianza-para-la-media" class="section level1">
<h1><strong>1. Intervalo de confianza para la media:</strong></h1>
<p>Para el intervalo de confianza para la media crearemos el indicador:
<strong>percepción de facilidad de labor docente, este indicador debe ir
del 0 al 10</strong>. Para ello nos basaremos en cinco variables que
responden a “En una escala del 1 al 4, donde 1 es”Muy difícil” y 4 -
“Muy fácil ¿Qué tan facil o difícil es realizar las siguientes
actividades vinculadas al quehacer docente?”</p>
<table>
<colgroup>
<col width="26%" />
<col width="73%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Nombre de variable</th>
<th align="center">Etiqueta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">P1_27_A</td>
<td align="center">¿Qué tan fácil o difícil es comunicarse y
retroalimentar y motivar a las y los estudiante</td>
</tr>
<tr class="even">
<td align="center">P1_27_B</td>
<td align="center">¿Atender los problemas socioemocionales de las y los
estudiantes?</td>
</tr>
<tr class="odd">
<td align="center">P1_27_C</td>
<td align="center">¿Virtualizar la enseñanza, adaptando y/o
complementando las sesiones de “Aprendo en casa”, según necesidades de
las y los estudiantes?</td>
</tr>
<tr class="even">
<td align="center">P1_27_D</td>
<td align="center">¿Coordinar y responder a la demanda de los padres y
madres de familia?</td>
</tr>
<tr class="odd">
<td align="center">P1_27_E</td>
<td align="center">¿Planificar actividades bajo el enfoque por
competencias del Currículo Nacional de la Educación Básica?</td>
</tr>
</tbody>
</table>
<div id="recordemos-los-pasos-para-construir-un-indicador"
class="section level3">
<h3>Recordemos los pasos para construir un indicador:</h3>
<ol style="list-style-type: decimal">
<li>Verificar que las variables correspondan al concepto.</li>
<li>Revisar el sentido de las categorías en el
cuestionario/diccionario</li>
<li>Si las categorías están en el correcto sentido, proceder a sumarlas;
si no lo están, proceder a recodificarlas para luego sumar.
<strong>Recuerda que para sumarlas deben ser variables tipo
numéricas.</strong></li>
<li>Una vez realizada la suma, identificar el mínimo y el máximo.</li>
<li>Restar a todos los valores el mínimo.</li>
<li>Al resultado, dividir por el máximo menos el mínimo (según lo
identificado anteriormente) para obtener valores entre 0 y 1.</li>
<li>Multiplicar por el número que será el nuevo máximo. Ej: si queremos
que el indice vaya de 0 a 100, multiplicar por 100, etc.</li>
</ol>
<p>Ya habíamos revisado previamente que las variables si están como
numéricas.</p>
<pre class="r"><code>data = data %&gt;%
  mutate(suma=P1_27_A+P1_27_A+P1_27_A+P1_27_A+P1_27_A+P1_27_A) #creamos la suma 
summary(data$suma) #identifico mínimo y máximo</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    6.00   12.00   12.00   14.96   18.00   24.00</code></pre>
<p>Procedo a crear el indicador</p>
<pre class="r"><code>data = data %&gt;%
  mutate(indicador = ((suma-6)/18)*10) #le restamos el mínimo y dividimos entre 24-6

  summary(data$indicador)#revisamos que se haya creado bien el indicador</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   3.333   3.333   4.975   6.667  10.000</code></pre>
<p>Ahora que hemos creado nuestro indicador, procedemos a calcular el
intervalo de confianza para su media.</p>
<pre class="r"><code>ic_media = ciMean(data$indicador)
ic_media</code></pre>
<pre><code>##          2.5%    97.5%
## [1,] 4.939254 5.010853</code></pre>
<p>Nuestra media poblacional se encuentra entre 4.9 y 5. Esto quiere
decir que tenemos una certeza del 95% de que el valor poblacional de la
<strong>percepción de facilidad de labor docente</strong> se encuentra
entre 4.9 y 5. Lo que se encuentra muy cercano al punto medio del
indicador (5).</p>
</div>
</div>
<div id="intervalos-de-confianza-para-una-proporción"
class="section level1">
<h1><strong>2.Intervalos de confianza para una proporción</strong></h1>
<p>Tengamos en consideración que para poder hallar el intervalo de
confianza para una proporción debemos determinar nuestro caso de éxito.
Asimismo, para hallar el intervalo de confianza para una proporción
nuestra variable debe ser categórica y debe representar una variable
dicotómica; es decir, una variable con solo dos categorías posibles.</p>
<p><em>Hallemos el intervalo de confianza para la proporción de los
docentes que tienen una ocupación adicional que genere ingresos (P1_16
1-Si, 2-No).</em></p>
<p>Necesitamos tener muy claro la frecuencia de nuestro caso de éxito
(1) y del total de casos.</p>
<pre class="r"><code>table(data$P1_16)</code></pre>
<pre><code>## 
##     1     2 
##  2471 16436</code></pre>
<p><em>Nuestro caso de éxito es haber recibido este tipo de apoyo, por
lo tanto el primer argumento que ingresaremos en el prop.test es 2471.
Por otro lado, el total de casos es 2471 + 16436. Con eso claro,
procedamos a calcular el intervalo de confianza.</em></p>
<pre class="r"><code>x = 2471 #almacenamos en &quot;x&quot; la frecuencia de nuestro caso de éxito
n = 2471 + 16436 #almacenamos en &quot;n&quot; el total de casos</code></pre>
<p>Hallamos el invervalo de confianza para una proporción con el comando
<strong>prop.test</strong></p>
<pre class="r"><code>ic_prop = prop.test(x,n)
ic_prop #llamamos a ic_prop para visualizar los resultados</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  x out of n, null probability 0.5
## X-squared = 10313, df = 1, p-value &lt; 2.2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.1259367 0.1355988
## sample estimates:
##         p 
## 0.1306923</code></pre>
<p>Lo que hallamos nos permite afirmar con un 95% de confianza que, a
nivel poblacional, el porcentaje de docentes que cuentan con una
ocupación adicional que genera ingresos se encuentra entre 12.6% y
13.6%.</p>
</div>
<div id="intervalo-de-confianza-de-una-media-según-grupo"
class="section level1">
<h1><strong>3.Intervalo de confianza de una media según
grupo</strong></h1>
<p>Hallemos el intervalo de confianza para el indicador de percepción de
facilidad de labor docente, según el dominio geográfico. En este caso,
queremos comparar según si son de la costa, sierra o selva. Para ello
debemos dejar fuera a los casos de Lima Metropolitana y crear una nueva
variable (region) que se base en dominio geográfico y realizar los
siguientes cambios si es costa norte, coste centro o costa sur que se
convierta en costa, si es selva que siga siendo selva y si es sierra
norte, sierra centro o sierra sur que se convierta en sierra.</p>
<pre class="r"><code>data = data %&gt;%
  filter(!(dominio_geografico == &quot;LIMA METROPOLITANA&quot;))%&gt;%
  mutate(region = case_when(dominio_geografico == &quot;COSTA NORTE&quot;|dominio_geografico == &quot;COSTA CENTRO&quot;| dominio_geografico == &quot;COSTA SUR&quot; ~ &quot;COSTA&quot;,
                            dominio_geografico == &quot;SELVA&quot; ~ &quot;SELVA&quot;,
                            dominio_geografico == &quot;SIERRA NORTE&quot;|dominio_geografico == &quot;SIERRA CENTRO&quot;| dominio_geografico == &quot;SIERRA SUR&quot; ~ &quot;SIERRA&quot;))</code></pre>
<pre class="r"><code>#VERSIÓN CORTA
#data = data %&gt;%
#  filter(!(dominio_geografico == &quot;LIMA METROPOLITANA&quot;))%&gt;%
#  mutate(region = case_when(dominio_geografico %in% c(&quot;COSTA NORTE&quot;,&quot;COSTA CENTRO&quot;,&quot;COSTA SUR&quot;) ~ &quot;COSTA&quot;,
#                            dominio_geografico == &quot;SELVA&quot; ~ &quot;SELVA&quot;,
#                            T ~ &quot;SIERRA&quot;))</code></pre>
<p>Revisemos que nuestros datos se hayan asignado bien</p>
<pre class="r"><code>table(data$dominio_geografico)</code></pre>
<pre><code>## 
##  COSTA CENTRO   COSTA NORTE     COSTA SUR         SELVA SIERRA CENTRO 
##          1554          2407          1056          3684          3394 
##  SIERRA NORTE    SIERRA SUR 
##          1391          3109</code></pre>
<pre class="r"><code>table(data$region)</code></pre>
<pre><code>## 
##  COSTA  SELVA SIERRA 
##   5017   3684   7894</code></pre>
<p>Ahora si procedemos a calcular el intervalo de confianza para la
media del indicador de percepción de facilidad de labor docente según
region.</p>
<pre class="r"><code>ic_grupo = data %&gt;%
  group_by(region) %&gt;%
  summarise(Media = mean(indicador, na.rm=T),
            min = ciMean(indicador, na.rm=T)[1],
            max = ciMean(indicador, na.rm=T)[2]
            )
ic_grupo</code></pre>
<pre><code>## # A tibble: 3 × 4
##   region Media   min   max
##   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 COSTA   5.19  5.12  5.26
## 2 SELVA   5.03  4.94  5.11
## 3 SIERRA  4.74  4.68  4.79</code></pre>
<p>Según nuestra tabla, podemos afirmar que hay un 95% de probabilidad
de que a nivel poblacional la media de los docentes de la sierra
perciben una menor facilidad en sus labores. Mientras que los de la
costa perciben sus labores como más sencillas. Veamos el gráfico para
complementar esta afirmación.</p>
<pre class="r"><code>ggplot(ic_grupo, aes(x= region, y =Media)) +
  geom_errorbar(aes(ymin=min, ymax=max), width = 0.2)+
   geom_text(aes(label=paste(round(Media, 2))), size=4)+
  xlab(&quot;Región&quot;) + ylab(&quot;Indicador de percepción de facilidad de labor docente&quot;)+
  theme_bw()</code></pre>
<p><img src="pd5_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Debemos que buscar traslape entre las barras, en este caso podemos
reafirmar que los docentes de la sierra perciben una menor facilidad en
sus labores a comparación de los de la selva o costa. Por otro lado, los
docentes de la selva, perciben mayor facilidad que los de la sierra,
pero menor que los de la costa. A pesar de estar muy cercanas sus
barras, sabemos que no hay traslape por la anterior tabla. Esta nos
indicaba que el límite superior de selva es de 5.11; mientras que el
límite inferior de costa es de 5.12.</p>
<div id="ejercicio" class="section level2">
<h2>Ejercicio</h2>
<ol style="list-style-type: decimal">
<li><p>Calcular el intervalo de confianza para la media de la variable
que mide el tiempo invertido en preparar las clase y labores
administrativas de lunes a viernes (P1_9_A_LV_MIN)</p></li>
<li><p>Calcular el intervalo de confianza para la proporción de personas
que recibieron apoyo psicológico y/o emocional (P1_13)</p></li>
<li><p>Calcula el intervalo de confianza para la media de la variable
P1_9_A_LV_MIN según sexo (P1_1)</p></li>
</ol>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
